### ISSUE TITLE
Fix data for plots

### ISSUE THREAD

**Issue by SvenNekula** [SvenNekula/Shiny-Dashboards#2]
Hi @JoshuaSimon @Mink-star2000

There's a problem with the data in regards to the plots. Some of the bigger cities of a county have the same name as the county in the data set (e.g. Landkreis Bamberg <-> Bamberg Stadt => Bamberg <-> Bamberg). This leads  to  some bars stacking and looking messed up in the plots, if one of those counties is in the plot. As there are quite a few counties with the same name it would be quite annoying to do this by hand, so we have to figure out how to fix this. I'll look into that in the next following days, but if you have any ideas, let me know! :)

**Comment by JoshuaSimon** [comment]
These cases can be distinguished by adding another feature from the data set. The city name occurs in `GEN`. The designation, whether it is "Kreis", "Kerisefreie Stadt", etc., is contained in `BEZ`. The data variable `gdata `can be expanded via 

`gdata <- geodata %>% as_tibble() %>% 
  select(c(BL, EWZ_BL, GEN, BEZ, EWZ, cases, cases_per_100k, 
           cases7_per_100k, deaths, death_rate))`

A quick solution for fixing the plots would be, that one changes the x data from `GEN` to a combintaion like `paste(BEZ, GEN)`, which result in `"Kreisfreie Stadt Bamberg"` and `"Landkreis Bamberg"`. The code line in the plot calls would then be `... ggplot(., aes(x=reorder(paste(BEZ, GEN), -cases), y=cases)) + ...`.

![Rplot](https://user-images.githubusercontent.com/39858834/124393393-93878900-dcfa-11eb-8e7f-b8a71048e13b.png)

**Comment by SvenNekula** [comment]
Thank you! Problem is fixed. :)
